/* Feel It hero layer — no rebuild; fills existing weather/trust/popular widgets. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=s=>window.esc?window.esc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function weatherText(code){const m={0:['☀️','Clear'],1:['🌤️','Mainly clear'],2:['⛅','Partly cloudy'],3:['☁️','Overcast'],45:['🌫️','Fog'],48:['🌫️','Freezing fog'],51:['🌦️','Drizzle'],53:['🌦️','Drizzle'],55:['🌧️','Drizzle'],61:['🌧️','Rain'],63:['🌧️','Rain'],65:['🌧️','Heavy rain'],71:['❄️','Snow'],73:['❄️','Snow'],75:['❄️','Heavy snow'],80:['🌦️','Showers'],81:['🌧️','Showers'],82:['⛈️','Heavy showers'],95:['⛈️','Thunderstorm'],96:['⛈️','Thunderstorm'],99:['⛈️','Thunderstorm']};return m[code]||['🌦️','Weather']}
  async function fillWeather(){const w=$('fiWeatherWidget');if(!w)return;let lat=27.741,lng=85.336;if(navigator.geolocation){try{const p=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{timeout:5000,maximumAge:1200000}));lat=p.coords.latitude;lng=p.coords.longitude}catch{}}try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,weather_code,wind_speed_10m`);const d=await r.json(),[i,t]=weatherText(d.current.weather_code);w.querySelector('.hero-weather-icon').textContent=i;w.querySelector('.hero-weather-text').textContent=`${t} · ${Math.round(d.current.temperature_2m)}°C · wind ${Math.round(d.current.wind_speed_10m)} km/h`;}catch{w.querySelector('.hero-weather-text').textContent='Weather unavailable — route conditions checked before departure';}}
  function fillTrust(){const e=$('fiHeroTrust');if(!e)return;e.innerHTML='<span>✓ Local riders</span><span>✓ Payment checked</span><span>✓ WhatsApp support</span>';}
  function fillPopular(){const h=$('fiPopularStrip');if(!h||!Array.isArray(window.tours))return;h.innerHTML=window.tours.filter(t=>!t.coming_soon).slice(0,8).map(t=>`<article class="popular-card" onclick="openTour('${esc(t.id)}')"><div class="popular-card-body"><div class="popular-card-region">${esc(t.region)}</div><div class="popular-card-title">${esc(t.title)}</div><div class="popular-card-price">${window.fmtNPR?window.fmtNPR(t.price):'Price on request'}</div></div></article>`).join('');}
  function boot(){fillTrust();fillWeather();fillPopular();setTimeout(fillPopular,1200)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
