
function viewApps(){if(!can('apps'))return deny();return `<div class="card"><h3>Applications</h3>${pendingApps().map(r=>`<div class="row"><strong>${esc(r.name)}</strong><button class="btn btn-p" onclick="approveApp('${esc(r.id||'')}','${esc(r.name)}','${esc(r.phone)}')">Confirm</button></div>`).join('')||'<p class="muted">None</p>'}</div>`;}
window.addRider=async()=>{const row={name:$('nr-name').value.trim(),phone:$('nr-phone').value.trim(),status:'approved'};if(!row.name||!row.phone){toast('Need name+phone');return;}await sb.from('riders').insert([row]);toast('Added');await refresh();render();};
window.approveApp=async(id,name,phone)=>{await sb.from('riders').insert([{name,phone,status:'approved'}]);if(id)await sb.from('guide_apps').delete().eq('id',id);toast('Confirmed');await refresh();render();};
function viewMessages(){if(!can('messages'))return deny();const by={};messages.forEach(m=>by[m.email]=m);return `<div class="card">${Object.values(by).map(m=>`<div><strong>${esc(m.name||m.email)}</strong><div class="muted">${esc((m.body||'').slice(0,80))}</div></div>`).join('')||'<p class="muted">None</p>'}</div>`;}
function viewTours(){if(!can('tours'))return deny();return `<div class="card"><h3>Prices</h3>${tours.map(t=>`<div class="row"><span>${esc(t.title)}</span><input id="tp-${esc(t.id)}" value="${esc(t.price)}" style="width:90px;margin:0"><input id="tpl-${esc(t.id)}" value="${esc(t.price_local||'')}" style="width:90px;margin:0"><button class="btn btn-p" onclick="saveTourPrice('${esc(t.id)}')">Save</button></div>`).join('')}</div>`;}
window.saveTourPrice=async id=>{const price=Number($('tp-'+id)?.value||0),price_local=Number($('tpl-'+id)?.value||0);await sb.from('tours').update({price,price_local}).eq('id',id);toast('Saved');await refresh();render();};
function viewFeatured(){if(!can('featured'))return deny();let feat=[];try{feat=JSON.parse(localStorage.getItem('feelit_featured_ids')||'[]');}catch(e){}return `<div class="card"><h3>Featured</h3>${tours.map(t=>`<label class="chk"><input type="checkbox" data-feat="${esc(t.id)}" ${feat.includes(t.id)?'checked':''}> ${esc(t.title)}</label>`).join('')}<button class="btn btn-p" onclick="saveFeatured()">Save</button></div>`;}
window.saveFeatured=()=>{const ids=[...document.querySelectorAll('[data-feat]:checked')].map(e=>e.getAttribute('data-feat'));localStorage.setItem('feelit_featured_ids',JSON.stringify(ids));toast('Saved');};
function viewMoney(){if(!can('money'))return deny();return `<div class="card"><h3>Costs</h3><label>Fuel</label><input id="m-fuel" value="${esc(localStorage.getItem('feelit_fuel_price')||'180')}"><label>Hotel</label><input id="m-hotel" value="${esc(localStorage.getItem('feelit_hotel_cost')||'2000')}"><label>Food</label><input id="m-food" value="${esc(localStorage.getItem('feelit_food_cost')||'1000')}"><label>Driver %</label><input id="m-driver" value="${esc(localStorage.getItem('feelit_driver_pct')||'40')}"><label>Owner %</label><input id="m-owner" value="${esc(localStorage.getItem('feelit_owner_pct')||'60')}"><button class="btn btn-p" onclick="saveMoney()">Save</button></div>`;}
window.saveMoney=()=>{localStorage.setItem('feelit_fuel_price',$('m-fuel').value);localStorage.setItem('feelit_hotel_cost',$('m-hotel').value);localStorage.setItem('feelit_food_cost',$('m-food').value);localStorage.setItem('feelit_driver_pct',$('m-driver').value);localStorage.setItem('feelit_owner_pct',$('m-owner').value);toast('Saved');};
function viewSettings(){if(!can('settings'))return deny();return `<div class="card"><h3>Settings</h3><label>Hero image</label><input id="s-bg" value="${esc(localStorage.getItem('feelit_hero_bg')||'assets/1.png')}"><button class="btn btn-p" onclick="saveSettings()">Save</button></div>`;}
window.saveSettings=()=>{localStorage.setItem('feelit_hero_bg',$('s-bg').value);toast('Saved');};
function viewStaff(){if(!can('staff'))return deny();const list=loadStaffRoles();return `<div class="card"><h3>Owner</h3><p class="muted">${OWNERS.join(', ')}</p></div><div class="card"><h3>Add staff</h3><label>Email</label><input id="st-email"><label>Name</label><input id="st-name"><label>Password</label><input id="st-pass" type="password"><div class="perm-grid">${ALL_PERMS.filter(p=>p!=='staff').map(p=>`<label><input type="checkbox" value="${p}"> ${esc(PERM_LABELS[p])}</label>`).join('')}</div><button class="btn btn-p" onclick="saveStaffMember()">Save staff</button></div><div class="card"><h3>Staff</h3>${list.map((s,i)=>`<div class="row"><strong>${esc(s.email)}</strong><button class="btn btn-d" onclick="removeStaff(${i})">Remove</button></div>`).join('')||'<p class="muted">None</p>'}</div>`;}
window.saveStaffMember=async()=>{const email=($('st-email').value||'').trim().toLowerCase();const name=($('st-name').value||'').trim();const pass=($('st-pass').value||'').trim();if(!email){toast('Email required');return;}if(isOwnerEmail(email)){toast('Owner email');return;}const perms=emptyPerms();document.querySelectorAll('.perm-grid input:checked').forEach(el=>{if(el.value)perms[el.value]=true;});const list=loadStaffRoles();const idx=list.findIndex(s=>s.email===email);const row={email,name,perms,active:true,pass_hash:idx>=0?list[idx].pass_hash:null};if(pass)row.pass_hash=await sha256(pass);if(idx>=0)list[idx]={...list[idx],...row};else list.push(row);saveStaffRoles(list);toast('Staff saved');render();};
window.removeStaff=i=>{const list=loadStaffRoles();list.splice(i,1);saveStaffRoles(list);render();};
boot();
